### ISSUE TITLE
Question: Why the modules

### ISSUE THREAD

**Issue by Allann** [antosubash/AbpMinimalApiHelloWorld#1]
Hi,

I just watched the video and read the blog about this solution and being new to ABP I have a couple questions.

- Why replace default DI with Autofac, is there something special needed by ABP that makes this a requirement? 
- With this being minimal Api, why then add Mvc back into the mix?

The whole reason as I understand it regarding the introduction of minimal Apis as introduced by Microsoft is to allow the developer to only add the parts they need to improve perf.

**Comment by antosubash** [comment]
Why replace default DI with Autofac, is there something special needed by ABP that makes this a requirement?
- Autofac is the DI used by the ABP framework. We need that to use the framework features.
With this being minimal Api, why add Mvc back into the mix?
- ABP framework provides a lot of features out of the box. That is the main reason people use the framework so they don't have to reinvent the wheel. 

This post was to show how to use the Minimal API with the ABP framework and ABP has a dependency on MVC.

**Comment by Allann** [comment]
Thankyou. That all makes sense.
